language: python
dist: bionic

python:
  - "3.8"
  - "3.9"
  - "3.10"

install:
  - pip install -U tox-travis coverage coveralls poetry

script:
  - tox
  - coverage run --source flake8_tensors -L -m flake8 test/test.py  --select WT

after_success:
  - coveralls
