language: python
dist: bionic

python:
  - "3.8"
  - "3.9"

install:
  - pip install -U tox-travis coverage coveralls
  - pip install -U -r requirements.txt


script:
  - tox
  - coverage run -m flake8 test/test.py --source flake8_tensors -L --select WT

after_success:
  - coveralls
