image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python38-x64"

install:
    - "%PYTHON%\\python.exe -m pip install tox"

test_script:
    - "%PYTHON%\\python.exe -m tox"
